# Config file for uuid-world-converter
# https://github.com/legendnightt/uuid-world-converter

# Server Directory
# server
#   for vanilla server
# server/server
#   for MCDR server
server_directory: server/server

# World Directory
world_directory: world

# Changing /server uuids
# IMPORTANT: used for getting player names for getting uuids
files:
  - name: whitelist.json
    enable: true
  - name: ops.json
    enable: true
  - name: banned-players.json
    enable: true

# Changing /world uuids
folders:
  - name: playerdata
    enable: true
  - name: stats
    enable: true
  - name: advancements
    enable: true


